const FETCH_FEED = 'FETCH_FEED';
const FETCH_COUNTRY_FEED = 'FETCH_COUNTRY_FEED';
const GET_ARTICLE = 'GET_ARTICLE';
const GET_NEWS = 'GET_NEWS'
const SET_NEWS = 'SET_NEWS';
const SET_NEWS_COUNTRY = 'SET_NEWS_COUNTRY';
const SET_ARTICLE_DETAIL = 'SET_ARTICLE_DETAIL'

export {
  FETCH_FEED,
  FETCH_COUNTRY_FEED,
  GET_ARTICLE,
  GET_NEWS,
  SET_NEWS,
  SET_NEWS_COUNTRY,
  SET_ARTICLE_DETAIL
};
